# This is a file for using Docker with this project locally
# Do not worry about this file for now!
version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aa-curriculum/music-app
    command:
      sh -c "rm -f tmp/pids/server.pid && rails assets:precompile && bundle exec rails s -p 3000 -b
      '0.0.0.0'"
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres@db"